//
//  Music.swift
//  (null)
//
//  Created by (null) on 01/11/2016.
//  Copyright (c) 2016 (null). All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class PlayerProgressBarView: UIView {
    
    private var _progress: Double = 0
    public var progress: Double {
        set {
            _progress = newValue
            setNeedsDisplay()
        }
        get {
            return _progress
        }
    }
    
    public override func draw(_ rect: CGRect) {
        drawProgressBar(position: _progress, width: frame.width)
    }
    
    public func drawProgressBar(position: Double, width: CGFloat) {
        let color = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 0.300)
        let rectanglePath = UIBezierPath(rect: CGRect(x: 0, y: 0, width: CGFloat(position) * width, height: 80))
        color.setFill()
        rectanglePath.fill()
    }
}

